server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy que envía el tráfico a la IP privada de tu EC2-App (Backend)
    location /alumnos {
        proxy_pass http://10.0.1.234:8080/alumnos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
