server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /alumnos {
        # Sin la barra final para que coincida exactamente con tu @RequestMapping
        proxy_pass http://10.0.1.175:8080/alumnos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
